### ISSUE TITLE
No obvious way to quit

### ISSUE THREAD

**Issue by cooljeanius** [kreativekorp/pushchar#1]
After opening `pushchar.jar`, there's no obvious way to get rid of its button from the screen. Clicking the red "close window" button only gets rid of that one window, there's no "quit" menu option, it can't be made to Force Quit from the system's Force Quit menu, there's no `PushChar` process that shows up in Activity Monitor to kill there, nor is there a launchctl job for it that shows up under `launchctl list` that can be removed with `launchctl remove`. If there's something I'm missing, please let me know, but it really should be easier to get rid of the PushChar button.

**Comment by RebeccaRGB** [comment]
Right-clicking the button now opens a menu with a quit option.

**Comment by cooljeanius** [comment]
Thanks!
